spring:
  datasource:
    url: jdbc:postgresql://ep-round-water-afp2ywv7-pooler.c-2.us-west-2.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_s9ULNfBWok0O
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
